import Head from "next/head";
import Header from "@/components/header";
import React, { useState, useEffect } from "react";

const Home: React.FC = () => {
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  const [username, setUsername] = useState<string>("guest");

  
  useEffect(() => {
    const loggedInUser = sessionStorage.getItem("loggedInUser");

    if (loggedInUser) {
      try {
        const parsedUser = JSON.parse(loggedInUser);
        if (parsedUser?.username) {
          setUsername(parsedUser.username);
          setIsLoggedIn(true);
        }
      } catch (error) {
        console.error("Error parsing loggedInUser", error);
      }
    }
  }, []);

  return (
    <>
      <Head>
        <title>BookMarkt</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header />
        <main className="p-1 flex-grow flex justify-center items-center">
          <section>
            {isLoggedIn ? 
              <h2>Welcome, {username}</h2>
            :
              <h2>Welcome, stranger</h2>
            }
            {isLoggedIn ? 
             <p>With BookMarkt you can easily <br />search and buy books.</p> 
            : 
             <p>Login/register first to<br />search and buy books.</p>
            }
          </section>
        </main>
      </div>
    </>
  );
};

export default Home;
