import Head from "next/head";
import Header from "@/components/header";
// import { Inter } from "next/font/google";


import React from "react";
// const inter = Inter({ subsets: ["latin"] });

const Home: React.FC = () => {
  return (
    <>
      <Head>
        <title>BookMarkt</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div >
        <Header></Header>
      <main className="p-1 flex-grow flex justify-center items-center">
        <section>
          <h2>Home</h2>
          <p>Welcome to BookMarkt</p>
        </section>
      </main>
      </div>
    </>
  );
}
export default Home;