import Head from "next/head";
import Header from "@/components/header";
import React, { useState, useEffect } from "react";
import { useTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";

const Home: React.FC = () => {
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  const [username, setUsername] = useState<string>("guest");
  const { t } = useTranslation(); 

  
  useEffect(() => {
    const loggedInUser = sessionStorage.getItem("loggedInUser");

    if (loggedInUser) {
      try {
        const parsedUser = JSON.parse(loggedInUser);
        if (parsedUser?.username) {
          setUsername(parsedUser.username);
          setIsLoggedIn(true);
        }
      } catch (error) {
        console.error("Error parsing loggedInUser", error);
      }
    }
  }, []);

  return (
    <>
      <Head>
        <title>BookMarkt</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header />
        <main className="p-1 flex-grow flex justify-center items-center">
          <section>
            {isLoggedIn ? 
              <h2>{t('home.welcome')} {username}</h2>
            :
              <h2>{t('home.welcome')}</h2>
            }
            {isLoggedIn ? 
             <p>{t('home.textLoggedIn')}</p> 
            : 
             <p>{t('home.textNotLoggedIn')}</p>
            }
          </section>
        </main>
      </div>
    </>
  );
};

export const getServerSideProps = async (context) => {
  const { locale } = context;
  return {
      props: {
          ...(await serverSideTranslations(locale ?? "en", ["common"])),
      },
  };
};

export default Home;
